const https = require('https');
const querystring = require('querystring');

exports.handler = async function(event) {
  const code = event.queryStringParameters && event.queryStringParameters.code;
    const error = event.queryStringParameters && event.queryStringParameters.error;

      const CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
        const CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
          const REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI;

            // Handle OAuth errors from Google
              if (error) {
                  return {
                        statusCode: 302,
                              headers: { Location: `/?auth_error=${encodeURIComponent(error)}` }
                                  };
                                    }

                                      // Step 1: No code yet — redirect to Google OAuth consent screen
                                        if (!code) {
                                            const SCOPES = [
                                                  'https://www.googleapis.com/auth/spreadsheets',
                                                        'https://www.googleapis.com/auth/documents.readonly',
                                                              'https://www.googleapis.com/auth/gmail.send',
                                                                    'https://www.googleapis.com/auth/drive.readonly'
                                                                        ].join(' ');

                                                                            const params = querystring.stringify({
                                                                                  client_id: CLIENT_ID,
                                                                                        redirect_uri: REDIRECT_URI,
                                                                                              response_type: 'code',
                                                                                                    scope: SCOPES,
                                                                                                          access_type: 'offline',
                                                                                                                prompt: 'consent'
                                                                                                                    });
                                                                                                                    
                                                                                                                        return {
                                                                                                                              statusCode: 302,
                                                                                                                                    headers: { Location: `https://accounts.google.com/o/oauth2/v2/auth?${params}` }
                                                                                                                                        };
                                                                                                                                          }
                                                                                                                                          
                                                                                                                                            // Step 2: Exchange code for tokens
                                                                                                                                              try {
                                                                                                                                                  const tokens = await exchangeCode(code, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI);
                                                                                                                                                      const params = new URLSearchParams({
                                                                                                                                                            access_token: tokens.access_token,
                                                                                                                                                                  refresh_token: tokens.refresh_token || '',
                                                                                                                                                                        expires_in: tokens.expires_in || 3600,
                                                                                                                                                                              token_type: tokens.token_type || 'Bearer'
                                                                                                                                                                                  });
                                                                                                                                                                                  
                                                                                                                                                                                      return {
                                                                                                                                                                                            statusCode: 302,
                                                                                                                                                                                                  headers: { Location: `/?${params.toString()}` }
                                                                                                                                                                                                      };
                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                            return {
                                                                                                                                                                                                                  statusCode: 302,
                                                                                                                                                                                                                        headers: { Location: `/?auth_error=${encodeURIComponent(err.message)}` }
                                                                                                                                                                                                                            };
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                              };
                                                                                                                                                                                                                              
                                                                                                                                                                                                                              function exchangeCode(code, clientId, clientSecret, redirectUri) {
                                                                                                                                                                                                                                return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                    const body = querystring.stringify({
                                                                                                                                                                                                                                          code,
                                                                                                                                                                                                                                                client_id: clientId,
                                                                                                                                                                                                                                                      client_secret: clientSecret,
                                                                                                                                                                                                                                                            redirect_uri: redirectUri,
                                                                                                                                                                                                                                                                  grant_type: 'authorization_code'
                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                          const options = {
                                                                                                                                                                                                                                                                                hostname: 'oauth2.googleapis.com',
                                                                                                                                                                                                                                                                                      path: '/token',
                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                                                          'Content-Type': 'application/x-www-form-urlencoded',
                                                                                                                                                                                                                                                                                                                  'Content-Length': Buffer.byteLength(body)
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                const req = https.request(options, (res) => {
                                                                                                                                                                                                                                                                                                                                      let data = '';
                                                                                                                                                                                                                                                                                                                                            res.on('data', chunk => { data += chunk; });
                                                                                                                                                                                                                                                                                                                                                  res.on('end', () => {
                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                    const parsed = JSON.parse(data);
                                                                                                                                                                                                                                                                                                                                                                              if (parsed.error) reject(new Error(parsed.error_description || parsed.error));
                                                                                                                                                                                                                                                                                                                                                                                        else resolve(parsed);
                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                          reject(new Error('Failed to parse token response'));
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                req.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                                                                                                    req.write(body);
                                                                                                                                                                                                                                                                                                                                                                                                                                        req.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
