[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/auth-google"
  status = 302
  force = true
  conditions = {Query = {code = ":code"}}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
